services:
  tf2110-cu112-cd81-py38:
    image: tf2110-cu112-cd81-py38-img
    container_name: "tf2110-cu112-cd81-py38-ctn"
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib64
      #- DISPLAY=0.0
      #- WAYLAND_DISPLAY=wayland-0
      #- XDG_RUNTIME_DIR=/run/user/1002/
      #- PULSE_SERVER=/mnt/wslg/PulseServer
      #- LD_LIBRARY_PATH=/usr/lib/wsl/lib
    restart: always
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- /mnt/wslg:/mnt/wslg
      #- /usr/lib/wsl:/usr/lib/wsl
      - /mnt/f:/mnt
      - ../:/home/user/code
    devices:
      - /dev/usb:/dev/usb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8887:8887"

