services:
  tf2110-cu112-cd81-py38:
    image: tf2110-cu112-cd81-py38-img
    container_name: "tf2110-cu112-cd81-py38-ctn"
    build: 
      context: ./
      dockerfile: ./Dockerfile
    environment:
      #- XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      #- LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
      - DISPLAY=$DISPLAY
      #- WAYLAND_DISPLAY=wayland-0
    restart: always
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/f:/mnt
      - ../:/home/user/code
    devices:
      - /dev/usb:/dev/usb
    #https://docs.docker.com/compose/how-tos/gpu-support/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8887:8887"

